#version: 1.0.1

FROM centos-6.8-base-custom:latest
MAINTAINER   wandapeng "dapeng.wan@pintuibao.cn"
###########配置服务自启动##########
COPY run.sh send-weixin-info.sh /deploy/scripts/
RUN ln -s /deploy/scripts/send-weixin-info.sh /usr/bin/send-wx
RUN chmod 755 /deploy/scripts/*.sh
ENTRYPOINT ["/deploy/scripts/run.sh"]
###########发布相关端口##########
EXPOSE 22
EXPOSE 20882
###########安装##########
RUN mkdir -p /opt/ares-pay-provider/logs/
RUN mkdir -p /opt/ares-pay-provider/config/
WORKDIR /opt/ares-pay-provider/
COPY bin/ /opt/ares-pay-provider/bin/
RUN chmod 755 /opt/ares-pay-provider/bin/*
###############加载经常变化的数据文件进入镜像文件
COPY libs/ /opt/ares-pay-provider/libs/
COPY ares-pay-provider.jar /opt/ares-pay-provider/
###########创建数据卷目录##########
VOLUME    /opt/ /var/log/

